# Generated by Django 6.0.4 on 2026-05-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction_projects', '0002_alter_project_options_project_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SKILLED', 'Skilled Workers'), ('UNSKILLED', 'Unskilled Workers'), ('PLANT_OPERATOR', 'Plant Operators'), ('PROFESSIONAL', 'Professional Team')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(choices=[('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('STEEL_FIXER', 'Steel Fixer'), ('WELDER', 'Welder'), ('CARPENTER', 'Carpenter'), ('MASON', 'Mason'), ('PAINTER', 'Painter'), ('LABORER', 'Laborer'), ('CRANE_OPERATOR', 'Crane Operator'), ('EXCAVATOR_OPERATOR', 'Excavator Operator'), ('MIXER_OPERATOR', 'Mixer Operator'), ('ENGINEER', 'Engineer'), ('ARCHITECT', 'Architect'), ('SURVEYOR', 'Surveyor'), ('SUPERVISOR', 'Supervisor'), ('PROJECT_MANAGER', 'Project Manager'), ('OTHER', 'Other')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='workers.workercategory')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('is_present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_attendances', to='construction_projects.project')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workers.worker')),
            ],
            options={
                'unique_together': {('worker', 'project', 'date')},
            },
        ),
    ]
