# Generated by Django 6.0.4 on 2026-05-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date when project was completed', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes about project completion'),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_photo',
            field=models.ImageField(blank=True, help_text='Photo when project is completed', null=True, upload_to='project_completion_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, help_text='Main project photo', null=True, upload_to='project_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(help_text='Project manager assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total actual cost of the project', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
