# Generated by Django 6.0.4 on 2026-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person for the job', max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
