# Generated by Django 6.0.4 on 2026-05-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person for the job (e.g., Project Manager)', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number (e.g., +254704071967)', max_length=20),
        ),
    ]
