# Generated by Django 6.0.4 on 2026-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_alter_servicerequest_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office address', max_length=300),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='office_phone',
            field=models.CharField(blank=True, help_text='Office phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='personal_phone',
            field=models.CharField(blank=True, help_text='Personal mobile number', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person for the job', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
