# Generated by Django 6.0.4 on 2026-05-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_projects', '0001_initial'),
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='minimum_stock_level',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='material',
            name='reorder_quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='required_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total budgeted cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity needed for the project', max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='used_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of used materials', max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='used_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity already used', max_digits=10),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of this usage', max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='construction_projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, help_text='Amount used in this session', max_digits=10),
        ),
    ]
