# Generated by Django 6.0.4 on 2026-05-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_projects', '0002_alter_project_options_project_completed_at_and_more'),
        ('stock_management', '0002_remove_material_minimum_stock_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='construction_projects.project'),
        ),
        migrations.AlterField(
            model_name='material',
            name='required_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='used_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='used_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
