# Generated by Django 6.0.4 on 2026-05-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_alter_material_project_alter_material_required_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
    ]
