# Generated by Django 6.0.4 on 2026-05-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the incident', max_length=200)),
                ('incident_type', models.CharField(choices=[('SAFETY', 'Safety Hazard'), ('QUALITY', 'Quality Issue'), ('ACCIDENT', 'Accident'), ('THEFT', 'Theft/Loss'), ('OTHER', 'Other')], help_text='Type of incident', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Severity level', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('location', models.CharField(blank=True, help_text='Where on site did this occur?', max_length=300)),
                ('photo', models.ImageField(blank=True, help_text='Upload photo of the incident or hazard', null=True, upload_to='incident_photos/')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='How was this resolved?')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(help_text='Which project does this belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='construction_projects.project')),
            ],
        ),
    ]
